#!/bin/bash
# Context Bus v3 — Rolling Summary Generator
# Generates a structured summary for model handoffs

set -e

WORKSPACE="${CONTEXT_BUS_WORKSPACE:-$(pwd)}"
CONTEXT_DIR="$WORKSPACE/.context-bus"
HANDOFF_FILE="$CONTEXT_DIR/handoff.json"
SUMMARY_FILE="$CONTEXT_DIR/rolling-summary.md"

# Read handoff data
if [[ ! -f "$HANDOFF_FILE" ]]; then
    echo "No handoff.json found" >&2
    exit 1
fi

handoff=$(cat "$HANDOFF_FILE")

# Extract fields
timestamp=$(date -Iseconds)
author=$(echo "$handoff" | jq -r '.model.current // "unknown"')
task_desc=$(echo "$handoff" | jq -r '.task.description // "No active task"')
task_status=$(echo "$handoff" | jq -r '.task.status // "idle"')
task_project=$(echo "$handoff" | jq -r '.task.project // "unknown"')
usage=$(echo "$handoff" | jq -r '.model.usage_percent // 0')

# Extract arrays
recent_actions=$(echo "$handoff" | jq -r '.context.recent_actions // [] | .[-5:] | .[]' 2>/dev/null | sed 's/^/- /')
decisions=$(echo "$handoff" | jq -r '.context.decisions // [] | .[-5:] | .[]' 2>/dev/null | sed 's/^/- /')
next_steps=$(echo "$handoff" | jq -r '.context.next_steps // [] | .[-5:] | .[]' 2>/dev/null | sed 's/^/1. /' | nl -w1 -s'. ')
blockers=$(echo "$handoff" | jq -r '.context.blockers // [] | .[]' 2>/dev/null | sed 's/^/- /')
files=$(echo "$handoff" | jq -r '.files_touched // [] | .[-10:] | .[]' 2>/dev/null | sed 's/^/- /')

# Model history
history_count=$(echo "$handoff" | jq -r '.model.history | length // 0')

# Generate summary
cat > "$SUMMARY_FILE" << EOF
---
schema_version: 3
generated: $timestamp
author: $author
usage_percent: $usage
---

# Agent Handoff Summary

## TL;DR
${task_desc} (Status: ${task_status})

## Current Focus
**Task:** ${task_desc}
**Project:** ${task_project}
**Status:** ${task_status}
**Usage:** ${usage}%

## Recent Progress
${recent_actions:-"- No recent actions recorded"}

## Key Decisions Made
${decisions:-"- No decisions recorded"}

## Immediate Next Steps
${next_steps:-"1. No next steps defined"}

## Blockers
${blockers:-"- None"}

## Files Modified
${files:-"- None recorded"}

## Model History
This agent has switched models ${history_count} time(s) in this session.

---
*Generated by Context Bus v3*
EOF

# Count tokens (rough estimate: 4 chars = 1 token)
char_count=$(wc -c < "$SUMMARY_FILE" | tr -d ' ')
token_estimate=$((char_count / 4))

# Update YAML frontmatter with token count
sed -i.bak "s/^---$/---\ntoken_count: $token_estimate/" "$SUMMARY_FILE" 2>/dev/null || \
sed -i '' "s/^---$/---\'$'\n''token_count: $token_estimate/" "$SUMMARY_FILE" 2>/dev/null || true
rm -f "${SUMMARY_FILE}.bak"

echo "Generated rolling-summary.md (~${token_estimate} tokens)"
